[tox]
envlist = py312-min,py312,py313,py314-coverage

[testenv]
deps = 
  pytest
commands = 
  pytest -q -s --pyargs morphops

[testenv:py312-min]
basepython = python3.12
deps =
  numpy == 1.26.4
  scipy == 1.12.0
  pytest
commands =
  pytest -q -s --pyargs morphops

[testenv:py314-coverage]
basepython = python3.14
deps =
  pytest
  pytest-cov
commands =
  pytest -q -s --cov=morphops --cov-report=term-missing --pyargs morphops
