name: Build

on: [push, pull_request]

jobs:
  build-with-pip:
    name: ${{ matrix.os }}/py${{ matrix.python-version }}/pip
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    env:
      MPLBACKEND: agg
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12', '3.13', '3.14']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display versions
        run: python -V; pip -V
      - name: Install dependencies and package
        shell: bash
        run: pip install -U -e .'[tests]'
      - name: Run tests
        if: ${{ matrix.os != 'ubuntu-latest' || matrix.python-version != '3.14' }}
        run: pytest --pyargs morphops
      - name: Run tests with coverage
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.14' }}
        run: pytest --cov=morphops --cov-report=term-missing --pyargs morphops
